# Usar una imagen oficial de OpenJDK como base
FROM eclipse-temurin:17-jdk-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo JAR generado en la carpeta target/
COPY target/*.jar app.jar

# Exponer el puerto en el que la aplicación se ejecuta (por defecto 8080)
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
